apiVersion: v1
kind: {{.Values.service.kind}}
metadata:
  name: {{.Values.service.metadata.name}}
spec:
  selector:
    app: {{.Values.service.spec.selector.app}}
  type: {{.Values.service.spec.type}}
  ports:
  - protocol: {{.Values.service.spec.ports.protcol}}
    port: {{.Values.service.spec.ports.port}}
    targetPort: {{.Values.service.spec.ports.targetPort}}
    nodePort: {{.Values.service.spec.ports.nodePort}}